name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  myToken:  # id of input
    description: 'A valid API token scoped to post comments on the repo'
    required: true
  label-string:  # id of input
    description: 'Labels to verify; please see docs for wording logic'
    required: false
  message:  # id of input
    description: 'Comment to post if conditions are met'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'feather'  
  color: 'purple'
