name: 'Bookish-Umbrella'
description: 'Label comments by flexible conditions'
inputs:
  # Absolutely required to function
  message:
    description: 'Comment to post if conditions are met'
    required: true
  myToken:
    description: 'A valid API token scoped to post comments on the repo'
    required: true
  
  # Ways to get an issue number, at least one is required
  columns: # Comma separated list of numbers
    description: 'Get all issues from the indicated columns'
    required: false
  issue-numbers: # Comma separated list of numbers
    description: 'Get the issue with the indicated number'
    required: false
  
  # Ways to filter
  all:
    description: 'Set this to true if to post a comment regardless of other factors'
    required: false
    default: false
  label-string:
    description: 'Labels to verify to post a comment; see docs for syntax'
    required: false
  stale-days:
    description: 'Number of days of inactivity to post a comment'
    required: false
    default: 0
  stale-by-assignee: # requires stale-days
    description: 'If the assignee left an issue stale, post a comment'
    required: false
    default: false
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'umbrella'  
  color: 'purple'
