name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  labels:  # id of input
    description: 'List of labels to verify; please see docs for wording logic'
    required: false
    default: ''
  message:  # id of input
    description: 'Comment to post if conditions are met'
    required: true
    default: ''
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'dist/index.js'
