name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  labels:  # id of input
    description: 'Semi-colon separated lists of labels to verify'
    required: false
    default: ''
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'dist/index.js'
