name: Issue Trigger
on:
  issues:
    types: [labeled]

jobs:
  test_bookish_umbrella:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Post Comment
        id: api-json
        uses: Aveline-art/bookish-umbrella@main
        with:
          # required
          message: 'This is an issue message'
          myToken: ${{ secrets.GITHUB_TOKEN }}
          # targets
          issue-numbers: ${{ github.event.issue.number }}
          columns: 16784461, 16784462
          # filters
          label-string: dependency