name: PR Trigger
on:
  pull_request:
    types: [labeled]

jobs:
  test_bookish_umbrella:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Post Comment
        id: api-json
        uses: Aveline-art/bookish-umbrella@main
        with:
          # required
          message: 'PATH text.md'
          myToken: ${{ secrets.GITHUB_TOKEN }}
          # targets
          issue-numbers: ${{ github.event.pull_request.number }}
          # filters
          label-string: "'good first issue'"